config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  root 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:amount, :company, :contragent, :currency, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<div class="col-xs-12">
<%= simple_form_for(@invoice) do |f| %>
  <div id="invoice-wrap">
    <%= f.error_notification %>
    <div class="row">
      <div class="col-xs-12">
        <h3 class="page-header">INVOICE<small class="pull-right">Date: <span class="invoice_header_date"></span></small></h3>
      </div><!-- /.col -->
    </div>

    <div class="row invoice-info">
      <div class="col-xs-4 invoice-col">
        From
        <address>
          <%= f.input_field :company, class: "form-control", id: "1" %>
          <input class="form-control" id= "2"  placeholder="address line 1" />
          <input class="form-control" id= "3"  placeholder="address line 2" />
          <input class="form-control" id= "4"  placeholder="phone number" />
        </address>
      </div><!-- /.col -->
      <div class="col-xs-4 invoice-col">
        To
        <address>
          <%= f.input_field :contragent, class: "form-control", id: "5" %>
          <input class="form-control" id= "6"  placeholder="address line 1" />
          <input class="form-control" id= "7"  placeholder="address line 2" />
          <input class="form-control" id= "8"  placeholder="phone number" />
        </address>
      </div><!-- /.col -->
      <div class="col-xs-4 invoice-col">
        <form class="form-horizontal">

          <div class="form-group">
            <div class="col-xs-4"><label>Invoice #</label></div>
            <div class="col-xs-8 invoice_num"><span id="invoice_number"><%= (Invoice.last.present? ? (Invoice.last.id + 1) : 1) %></span></div>
          </div>
          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-4"><%= f.label :date, required: false %></div>
            <div class="col-xs-8"><%= f.input_field :date, class: "form-control datepicker", as: :string, id: "invoice_date" %></div>
          </div>

          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-4"><%= f.label :currency, required: false %></div>
            <div class="col-xs-8"><%= f.input_field :currency, id:"invoice_currency", class: "form-control" %></div>
          </div>


          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-5 invoice_space"><label>Amount due</label></div>
            <div class="col-xs-7 invoice_space bold" style="text-align:right; padding-top:7px"><span class="due">875.00</span><span class="subtotal_currency"></span></div>
          </div>
        </form>
      </div><!-- /.col -->
    </div><!-- /.row -->

    <div class="row">
      <div class="col-xs-12 table-responsive">
        <hr>
        <table class="table table-hover" id="items">
      
          <thead>
              <th class="item-name">Item</th>
              <th class="description">Description</th>
              <th class="unit">Unit Cost</th>
              <th class="quantity">Quantity</th>
              <th class="units">Price</th>
              <th class="no_print">Actions</th>
          </thead>
      
          <tbody>
            <tr class="item-row">
              <td><input class="form-control item_name" value="Item #1" /></td>
              <td><input class="form-control item_desc" value="Description" /></td>
              <td><input class="form-control cost" value="650.00" /></td>
              <td><input class="form-control qty" value="1" /></td>
              <td class="price_td"><span class="price">650.00</span><span class="subtotal_currency"></span></td>
              <td class="delete_td"><a class="delete" href="javascript:;" title="Remove row"><span class="ti-close"></span></a></td>
            </tr>
          
            <tr class="item-row">
              <td><input class="form-control item_name" value="Item #2" /></td>

              <td><input class="form-control item_desc" value="Description #2" /></td>
              <td><input class="form-control cost" value="75.00" /></td>
              <td><input class="form-control qty" value="3" /></td>
              <td class="price_td"><span class="price">225.00</span><span class="subtotal_currency"></span></td>
              <td class="delete_td"><a class="delete" href="javascript:;" title="Remove row"><span class="ti-close"></span></a></td>
            </tr>
          
            <tr id="hiderow">
              <td colspan="6"><a id="addrow" class="btn btn-success btn-sm" href="javascript:;" title="Add a row"><span class="ti-plus"></span>  Add a row</a></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-xs-offset-6">
        <div class="table-responsive">
          <table class="table table-hover" id="totals">
            <tr>
              <th style="width:50%">Subtotal:</th>
              <td><span id="subtotal">875.00</span><span class="subtotal_currency"></span></td>
            </tr>
            <tr>
              <th>Tax:</th>
              <td><input id="9" class="form-control" value="0.00" /></td>
            </tr>
            <tr>
              <th>Total:</th>
              <td class="balance"><span class="due" id="invoice_total">875.00</span><span class="subtotal_currency"></span></td>
              <%=f.hidden_field :amount, id: "invoice_total1" %>
            </tr>
          </table>
        </div>
      </div><!-- /.col -->    
    </div>

    <div class="row">
      <div class="col-xs-12 pull-left">
        <a class="btn btn-info btn-sm" id="invoice_button" data-toggle="modal" data-target="#invoice_modal">Show Invoice</a>
        <%= f.button :submit, 'Submit Payment', class: 'btn btn-warning btn-sm', id: "submit_invoice" %>    
      </div>
    </div>

    <div id="terms">
      <h5>Terms</h5>
      <textarea id="10">Payment terms: net 30. Interest accrued at 1.5% per month thereafter.</textarea>
    </div>
  </div>
  <% end %>
</div>

<div class="modal fade" id="invoice_modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="width:920px">
      <div class="container-fluid invoice_wrapper" style="margin:10px" id="print-me">
        
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" onclick="printDiv('print-me')">Print</button>
      </div>
    </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center">Cotizador</h1>

<div class="container">
  <div class="card radius z-depth-3">
    <%= link_to new_invoice_path do %>
      <div class="btn-floating halfway-fab waves-light red"><i class="material-icons">add</i></div>
    <%end%>
    <div class="card-content">
      <table class="highlight responsive-table centered">
        <thead>
          <tr>
            <th>Cantidad</th>
            <th>Empresa/Pyme</th>
            <th>Contragent</th>
            <th>Moneda</th>
            <th>Fecha</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @invoices.each do |invoice| %>
            <tr>
              <td><%= invoice.amount %></td>
              <td><%= invoice.company %></td>
              <td><%= invoice.contragent %></td>
              <td><%= invoice.currency %></td>
              <td><%= invoice.date %></td>
              <td><%= link_to 'Ver', invoice, class:"waves-effect waves-light btn" %></td>
              <td><%= link_to 'Editar', edit_invoice_path(invoice), class:"waves-effect waves-light btn" %></td>
              <td><%= link_to invoice, method: :delete,class:" halfway-fab waves-effect waves-light  ", data: { confirm: "Seguro que quieres eliminar?" } do %>
                    <i class="material-icons">delete</i> 
                  <% end %>
              </td>
            </tr>
            
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/invoices/new.html.erb
<h1 class="center">New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @invoice.amount %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Contragent:</strong>
  <%= @invoice.contragent %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @invoice.currency %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
</header>

<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">one</a></li>
  <li class="divider"></li>
  <li><a href="#!">one</a></li>
</ul>

<nav>
  <div class="nav-wrapper z-depth-2">
    <a href="#!"><img class="responsive-img " src="" width="150" height="150"></img></a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      
      <li></li>
      <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Ajustes<i class="material-icons right">arrow_drop_down</i></a></li>
      
        <li></li>
        <li></li>
      
    </ul>
  </div>
  
  <!--Navbar Mobile-->
  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Quiénes somos</a></li>
    <li><a href="badges.html">¿Porque Genuine?</a></li>
    <li><a href="collapsible.html">Inversiones</a></li>
    <li><a href="mobile.html">Faq</a></li>
    <li><a href="mobile.html">Contacto</a></li>
    <li><div class="divider"></div></li>
    <li><a class="container waves-effect waves-light btn black-text">Iniciar Sesión </a></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cotizador</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>